const assert=require('node:assert/strict');
const {matches,scale,totals,dayKey}=require('../core.js');
const data=require('../data/foods.json');
const f={basis:{qty:100,unit:'g'},nutrients:[200,null,0,'Tr'],portion:{nutrients:[300,null,0,'Tr']}};
assert.deepEqual(scale(f,50,'g'),[100,null,0,'Tr']);
assert.deepEqual(scale(f,2,'portion'),[600,null,0,'Tr']);
for(const q of [0,-1,Infinity,NaN])assert.throws(()=>scale(f,q,'g'));
assert.throws(()=>scale(f,20,'ml'));
assert.deepEqual(totals([{calories:120,protein:null},{calories:null,protein:0}]),{calories:120,protein:0,unknownCalories:1,unknownProtein:1});
assert.equal(dayKey(new Date('2026-09-30T18:31:00Z')),'2026-10-01');
assert.equal(dayKey(new Date('2026-09-30T18:29:00Z')),'2026-09-30');
for(const query of ['idli','atukulu','varigalu','bhindi','palak','banana','paneer'])assert(data.foods.some(f=>matches(f,query)),query);
const millet=data.foods.find(f=>f.name==='Proso millet dry (varigalu)');
assert.equal(scale(millet,80,'g')[0],272.8);
const chapati=data.foods.find(f=>f.name==='Grainease chapati');
assert.equal(scale(chapati,80,'g')[1],null);
const rice=data.foods.filter(f=>matches(f,'rice'));
assert(rice.some(f=>f.preparation==='Raw / dry'));assert(rice.some(f=>f.preparation==='Cooked'));
console.log('PASS: serving maths, missing nutrients, timezone rollover, aliases, and raw/cooked rice.');
